/*
 * This source file was generated by the Gradle 'init' task
 */
package tictactoe;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        ticTacToe game = new ticTacToe();
        assertNotEquals(game.playMove(2, 'X'), false);
    }
}
