/*
 * This source file was generated by the Gradle 'init' task
 */
package tictactoe;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        ticTacToe game = new ticTacToe();
        Scanner scan = new Scanner(System.in);
        System.out.print("\033[H\033[2J");
        System.out.flush();
        int points[] = {0, 0};
        char tile[] = {'X', 'O'};
        int nextTurn = -1;
        boolean keepPlaying = true;
        boolean endGame = false;
        System.out.println("Let's play Tic-Tac-Toe!\nX's go first.");
        while(keepPlaying){
            while(!endGame){
                if(nextTurn == 0){
                    nextTurn = 1;
                }else{
                    nextTurn = 0;
                }
                game.displayBoard();
                System.out.println("Pick a number 1 - 9");
                keepPlaying = false;
                while(scan.hasNext()){
                    if(scan.hasNextInt()){
                        int num = scan.nextInt();
                        if(num > 10 || num < 0){
                            System.out.print("\033[H\033[2J");
                            System.out.flush();
                            System.out.println("This number is not between 1 to 9.");
                            game.displayBoard();
                        }else{
                            game.playMove(num, tile[nextTurn]);
                            if(game.checkWinner(nextTurn) > -1){
                                endGame = true;
                                break;
                            }
                        }
                    }else{
                        System.out.print("\033[H\033[2J");
                        System.out.flush();
                        System.out.println("This is not a valid input. Please put in a number from 1 to 9.");
                        game.displayBoard();
                    }
                }
            }
            if(game.checkWinner(nextTurn) != 2){
                System.out.println("Player " + String.valueOf(tile[nextTurn]) + " is the winner!");
                points[nextTurn]++;
            }
            //A value of 2 means draw
            while(scan.hasNext()){
                    String ans = scan.next();
                    if(ans.equalsIgnoreCase("yes")){
                        keepPlaying = true;
                        break;
                    }else if(ans.equalsIgnoreCase("no")){
                        keepPlaying = false;
                        break;
                    }else{
                        System.out.println("Please pick yes or no.");
                    }
                }
        }
        scan.close();
    }
}
